name: Merge CN List

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # 每天 UTC 时间凌晨 3 点运行

jobs:
  merge-cn-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up working directories
        run: |
          mkdir -p logs
          mkdir -p output
          > logs/cn_failed_downloads.log

      - name: Download cn_urls.txt
        run: |
          curl -sSL -o cn_urls.txt https://raw.githubusercontent.com/siren202101/Global_Compilation/refs/heads/main/cn_urls.txt

      - name: Download and process listed files
        run: |
          > combined_list.txt
          while IFS= read -r url; do
            if [[ "$url" =~ ^# || "$url" =~ ^DOMAIN- || "$url" =~ ^IP- || -z "$url" ]]; then
              continue
            fi
            echo "Downloading $url"
            content=$(curl -sSL "$url") || {
              echo "$url" >> logs/cn_failed_downloads.log
              continue
            }
            echo "$content" >> combined_list.txt
          done < cn_urls.txt

      - name: Clean combined list
        run: |
          # 删除注释、DOMAIN-、IP-
          sed -i '/^#/d' combined_list.txt
          sed -i '/^DOMAIN-/d' combined_list.txt
          sed -i '/^IP-/d' combined_list.txt

      - name: Download and clean accelerated-domains.china.conf
        run: |
          curl -sSL -o accelerated.conf https://fastly.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf
          sed -e 's/^server=\/\(.*\)\/114\.114\.114\.114/\1/' accelerated.conf > cleaned_accelerated.conf

      - name: Merge, deduplicate and save final list
        run: |
          cat combined_list.txt cleaned_accelerated.conf | sort -u > output/cn_list.conf
          

      - name: Force push updated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # 强制提交文件
          git add output/cn_list.conf logs/cn_failed_downloads.log
          git commit --amend --no-edit || echo "No changes to commit"

          # ✅ 用 PAT 明确推送（这个才会用 GG_TOKEN，而不是默认bot）
          git push https://x-access-token:${{ secrets.GG_TOKEN }}@github.com/siren202101/Global_Compilation.git HEAD:main --force
