name: Update CN List

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-cn-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GG_TOKEN }} # 使用 GG_TOKEN 检出仓库

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create directories
        run: |
          mkdir -p output
          mkdir -p logs

      - name: Download and process cn_urls.txt
        run: |
          curl -s -o cn_urls.txt https://raw.githubusercontent.com/siren202101/Global_Compilation/refs/heads/main/cn_urls.txt || echo "Failed to download cn_urls.txt" >> logs/cn_failed_downloads.log
          if [ -f cn_urls.txt ]; then
            grep -vE '^#|^DOMAIN-|^IP-' cn_urls.txt > cn_urls_cleaned.txt
          else
            echo "cn_urls.txt not found" >> logs/cn_failed_downloads.log
          fi

      - name: Download and process accelerated-domains.china.conf
        run: |
          curl -s -o accelerated-domains.china.conf https://fastly.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf || echo "Failed to download accelerated-domains.china.conf" >> logs/cn_failed_downloads.log
          if [ -f accelerated-domains.china.conf ]; then
            sed '/server=\//d; /\/114.114.114.114/d' accelerated-domains.china.conf > accelerated_domains_cleaned.txt
          else
            echo "accelerated-domains.china.conf not found" >> logs/cn_failed_downloads.log
          fi

      - name: Merge and deduplicate files
        run: |
          cat cn_urls_cleaned.txt accelerated_domains_cleaned.txt 2>/dev/null | sort -u > output/cn_list.conf
          touch output/cn_list.conf
          touch logs/cn_failed_downloads.log

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add output/cn_list.conf logs/cn_failed_downloads.log
          git commit -m "Update cn_list.conf and cn_failed_downloads.log" || exit 0
          git push https://x:${{ secrets.GG_TOKEN }}@github.com/siren202101/Global_Compilation.git main
