name: Update CN List

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨运行
  workflow_dispatch: # 支持手动触发

jobs:
  update-cn-list:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GG_TOKEN }} # 使用 GG_TOKEN 检出仓库

      # 安装 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 创建必要的目录
      - name: Create directories
        run: |
          mkdir -p output
          mkdir -p logs
          mkdir -p temp

      # 下载并处理 cn_urls.txt 中的 URL 列表
      - name: Download and process URLs from cn_urls.txt
        run: |
          curl -L -o cn_urls.txt https://raw.githubusercontent.com/siren202101/Global_Compilation/refs/heads/main/cn_urls.txt || echo "Failed to download cn_urls.txt at $(date)" >> logs/cn_failed_downloads.log
          if [ -f cn_urls.txt ]; then
            while IFS= read -r url; do
              # 跳过空行或注释行
              [[ -z "$url" || "$url" =~ ^# ]] && continue
              filename=$(echo "$url" | sha1sum | awk '{print $1}').txt
              curl -L -o "temp/$filename" "$url" || echo "Failed to download $url at $(date)" >> logs/cn_failed_downloads.log
              if [ -f "temp/$filename" ]; then
                grep -vE '^#|^DOMAIN-|^IP-' "temp/$filename" > "temp/$filename.cleaned"
              fi
            done < cn_urls.txt
          else
            echo "cn_urls.txt not found at $(date)" >> logs/cn_failed_downloads.log
          fi

      # 下载并处理 accelerated-domains.china.conf
      - name: Download and process accelerated-domains.china.conf
        run: |
          curl -L -o accelerated-domains.china.conf https://fastly.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf || echo "Failed to download accelerated-domains.china.conf at $(date)" >> logs/cn_failed_downloads.log
          if [ -f accelerated-domains.china.conf ]; then
            sed '/server=\//d; /\/114.114.114.114/d' accelerated-domains.china.conf > temp/accelerated_domains_cleaned.txt
          else
            echo "accelerated-domains.china.conf not found at $(date)" >> logs/cn_failed_downloads.log
          fi

      # 合并文件并去重
      - name: Merge and deduplicate files
        run: |
          cat temp/*.cleaned 2>/dev/null | sort -u > output/cn_list.conf
          touch output/cn_list.conf
          touch logs/cn_failed_downloads.log

      # 提交更改
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add output/cn_list.conf logs/cn_failed_downloads.log
          git commit -m "Update cn_list.conf and cn_failed_downloads.log" || exit 0
          git push https://x:${{ secrets.GG_TOKEN }}@github.com/siren202101/Global_Compilation.git main
